[package]
name = "nbreq"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
description = "Runtime-independent cancellable HTTP client"
publish = false

[features]
default = []
curl-pilot = ["dep:curl"]
curl-pilot-vendored = ["curl-pilot", "curl/ssl"]
native = []
test-support = []
ffi = []

[dependencies]
curl = { version = "=0.4.50", optional = true, default-features = false, features = ["poll_7_68_0", "nbreq-explicit-init"] }

[patch.crates-io]
curl = { path = "vendor/curl" }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
