[package]
name = "nbreq-f5-observe"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
publish = false
build = "build.rs"

[features]
default = ["resolver"]
resolver = ["nbreq/resolver"]
alloc-stats = ["dep:stats_alloc"]

[dependencies]
nbreq = { path = "../..", default-features = false, features = ["native"] }
stats_alloc = { version = "=0.1.10", optional = true }

[workspace]

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
