[package]
name = "nbreq-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.13"
nbreq = { path = "..", features = ["native"] }

[[bin]]
name = "native_response_decoder"
path = "fuzz_targets/native_response_decoder.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
