[package]
name = "nbreq-winpoll"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
description = "Windows polling compatibility support for NBReq"
license = "MIT OR Apache-2.0"
repository = "https://github.com/madandy24/nbreq"
readme = "README.md"
publish = ["crates-io"]
include = ["/src/**", "/README.md", "/LICENSE-APACHE", "/LICENSE-MIT"]

[dependencies]
windows-sys = { version = "=0.61.2", features = ["Win32_Networking_WinSock"] }

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
