[package]
name = "nbreq-winpoll"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
windows-sys = { version = "=0.61.2", features = ["Win32_Networking_WinSock"] }

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
