[package]
name = "nbreq-f5-memory"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
publish = false
build = "../build.rs"

[features]
default = ["resolver"]
resolver = ["nbreq/resolver"]
alloc-meter = ["dep:nbreq-f5-meter"]

[dependencies]
nbreq = { path = "../../..", default-features = false, features = ["native"] }
nbreq-f5-meter = { path = "meter", optional = true }
rustls = { version = "=0.23.42", default-features = false, features = ["ring", "std", "tls12"] }
rcgen = "=0.13.2"
time = { version = "=0.3.45", default-features = false, features = ["std"] }
serde_json = "=1.0.150"

[workspace]
exclude = ["meter"]

[lints.rust]
unsafe_code = "forbid"
warnings = "deny"

[lints.clippy]
unwrap_used = "deny"
